name: Execute tests and upload coverage reports

on:
  push:
    branches: "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test-and-coverage:
    name: Run Tests and Upload Coverage Reports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Workspace Tests with Coverage
        run: pnpm run test:coverage

      - name: Upload Backend Coverage
        uses: codecov/codecov-action@v6
        with:
          directory: ./backend/coverage/
          flags: backend
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload Frontend Coverage
        uses: codecov/codecov-action@v6
        with:
          directory: ./frontend/coverage/
          flags: frontend
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.2"

      - name: Go Test with Coverage
        working-directory: ./ext-api-service
        run: go test -v -coverprofile=coverage.out ./...

      - name: Upload Go Coverage
        uses: codecov/codecov-action@v6
        with:
          file: ./ext-api-service/coverage.out
          flags: ext-api-service
          token: ${{ secrets.CODECOV_TOKEN }}
